name: Update Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间的午夜执行
  workflow_dispatch:  # 添加手动触发器

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.5.1

    - name: Download and Update Files
      run: |
        curl -o delegated-apnic-latest https://ftp.apnic.net/stats/apnic/delegated-apnic-latest
        curl -o china_ip_list.txt https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
    - name: Generate Hash Values
      run: |
        sha256sum delegated-apnic-latest > delegated-apnic-latest.sha256
        sha256sum china_ip_list.txt > china_ip_list.txt.sha256

- name: Commit and Push Changes
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@users.noreply.github.com"
    git add -f delegated-apnic-latest china_ip_list.txt *.sha256
    git commit -m "Update files $(date +"%Y-%m-%d")"
    git push
